#!/usr/bin/env python3
"""Generate NpcConfig C++ class from npc.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def cpp_escape(value: str) -> str:
	return (
		value.replace("\\", "\\\\")
		.replace('"', '\\"')
		.replace("\n", "\\n")
		.replace("\r", "\\r")
		.replace("\t", "\\t")
	)


def load_entries(json_path: Path) -> list[dict]:
	with json_path.open("r", encoding="utf-8") as fp:
		data = json.load(fp)

	if not isinstance(data, list):
		raise ValueError(f"{json_path}: root must be a JSON array")

	entries: list[dict] = []
	for index, item in enumerate(data):
		if not isinstance(item, dict):
			raise ValueError(f"{json_path}: entry[{index}] must be an object")

		npc_id = item.get("id", 0)
		name = item.get("name", "")
		model = item.get("model", "")

		if not isinstance(npc_id, int):
			raise ValueError(f"{json_path}: entry[{index}].id must be an int")
		if not isinstance(name, str):
			raise ValueError(f"{json_path}: entry[{index}].name must be a string")
		if not isinstance(model, str):
			raise ValueError(f"{json_path}: entry[{index}].model must be a string")

		entries.append({"id": npc_id, "name": name, "model": model})

	return entries


def write_header(path: Path) -> None:
	path.parent.mkdir(parents=True, exist_ok=True)
	path.write_text(
		"""#pragma once

// AUTO-GENERATED by Game/Tool/gen_npc_config.py — do not edit by hand.

#include <game/GameApi.h>

#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

struct NpcConfigEntry
{
	int32_t id;
	char const* name;
	char const* model;
};

class GAME_API NpcConfig
{
public:
	static std::span<NpcConfigEntry const> All() noexcept;
	static std::size_t Count() noexcept;
	static NpcConfigEntry const* FindById(int32_t id) noexcept;
	static NpcConfigEntry const* FindByName(std::string_view name) noexcept;
};
""",
		encoding="utf-8",
		newline="\n",
	)


def write_source(path: Path, entries: list[dict], json_path: Path) -> None:
	path.parent.mkdir(parents=True, exist_ok=True)
	repo_root = Path(__file__).resolve().parents[2]
	try:
		source_path = json_path.resolve().relative_to(repo_root).as_posix()
	except ValueError:
		source_path = json_path.name

	lines = [
		"#include <game/generated/NpcConfig.gen.h>",
		"",
		"// AUTO-GENERATED by Game/Tool/gen_npc_config.py — do not edit by hand.",
		f"// Source: {source_path}",
		"",
		"namespace",
		"{",
		"\tNpcConfigEntry const kNpcEntries[] =",
		"\t{",
	]

	if entries:
		for entry in entries:
			lines.append(
				f'\t\t{{ {entry["id"]}, "{cpp_escape(entry["name"])}", "{cpp_escape(entry["model"])}" }},'
			)
	else:
		# Keep a valid array object even when empty; Count() returns 0.
		lines.append('\t\t{ 0, "", "" },')

	lines.extend(
		[
			"\t};",
			"} // namespace",
			"",
			"std::span<NpcConfigEntry const> NpcConfig::All() noexcept",
			"{",
			"\treturn std::span<NpcConfigEntry const>(kNpcEntries, Count());",
			"}",
			"",
			"std::size_t NpcConfig::Count() noexcept",
			"{",
			f"\treturn {len(entries)};",
			"}",
			"",
			"NpcConfigEntry const* NpcConfig::FindById(int32_t id) noexcept",
			"{",
			"\tfor (NpcConfigEntry const& entry : All())",
			"\t{",
			"\t\tif (entry.id == id)",
			"\t\t{",
			"\t\t\treturn &entry;",
			"\t\t}",
			"\t}",
			"\treturn nullptr;",
			"}",
			"",
			"NpcConfigEntry const* NpcConfig::FindByName(std::string_view name) noexcept",
			"{",
			"\tfor (NpcConfigEntry const& entry : All())",
			"\t{",
			"\t\tif (name == entry.name)",
			"\t\t{",
			"\t\t\treturn &entry;",
			"\t\t}",
			"\t}",
			"\treturn nullptr;",
			"}",
			"",
		]
	)

	path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
	parser = argparse.ArgumentParser(description="Generate NpcConfig C++ class from npc.json")
	parser.add_argument("--input", type=Path, required=True, help="Path to npc.json")
	parser.add_argument("--header", type=Path, required=True, help="Output header path")
	parser.add_argument("--source", type=Path, required=True, help="Output source path")
	args = parser.parse_args(argv)

	entries = load_entries(args.input.resolve())
	write_header(args.header.resolve())
	write_source(args.source.resolve(), entries, args.input.resolve())

	print(f"Generated {args.header} and {args.source} ({len(entries)} npc entries)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
