#!/usr/bin/env python3
"""Generate NpcConfig C++ class from npc.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def cpp_escape(value: str) -> str:
	return (
		value.replace("\\", "\\\\")
		.replace('"', '\\"')
		.replace("\n", "\\n")
		.replace("\r", "\\r")
		.replace("\t", "\\t")
	)


def optional_string(item: dict, key: str, index: int, json_path: Path) -> str:
	value = item.get(key)
	if value is None:
		return ""
	if not isinstance(value, str):
		raise ValueError(f"{json_path}: entry[{index}].{key} must be a string")
	return value


def load_textures(item: dict, index: int, json_path: Path) -> dict[str, str]:
	textures = item.get("textures")
	if textures is None:
		return {"albedo": "", "metalness_glossiness": "", "normal": ""}
	if not isinstance(textures, dict):
		raise ValueError(f"{json_path}: entry[{index}].textures must be an object")

	def pick(*keys: str) -> str:
		for key in keys:
			value = textures.get(key)
			if value is None:
				continue
			if not isinstance(value, str):
				raise ValueError(f"{json_path}: entry[{index}].textures.{key} must be a string")
			return value
		return ""

	# Engine slot names preferred; UE-style DA/DCSE/NR aliases accepted.
	return {
		"albedo": pick("albedo", "da", "DA"),
		"metalness_glossiness": pick("metalness_glossiness", "dcse", "DCSE"),
		"normal": pick("normal", "nr", "NR"),
	}


def load_entries(json_path: Path) -> list[dict]:
	with json_path.open("r", encoding="utf-8") as fp:
		data = json.load(fp)

	if not isinstance(data, list):
		raise ValueError(f"{json_path}: root must be a JSON array")

	entries: list[dict] = []
	for index, item in enumerate(data):
		if not isinstance(item, dict):
			raise ValueError(f"{json_path}: entry[{index}] must be an object")

		npc_id = item.get("id", 0)
		name = item.get("name", "")
		model = item.get("model")
		models = item.get("models")

		if not isinstance(npc_id, int):
			raise ValueError(f"{json_path}: entry[{index}].id must be an int")
		if not isinstance(name, str):
			raise ValueError(f"{json_path}: entry[{index}].name must be a string")

		resolved: list[str] = []
		if models is not None:
			if not isinstance(models, list) or not all(isinstance(path, str) for path in models):
				raise ValueError(f"{json_path}: entry[{index}].models must be an array of strings")
			resolved.extend(models)
		if model is not None:
			if not isinstance(model, str):
				raise ValueError(f"{json_path}: entry[{index}].model must be a string")
			if model and model not in resolved:
				# Single-model field remains supported; prepend if models also present.
				resolved.insert(0, model) if models is not None else resolved.append(model)

		if not resolved:
			raise ValueError(f"{json_path}: entry[{index}] needs model or models")

		entries.append(
			{
				"id": npc_id,
				"name": name,
				"models": resolved,
				"material": optional_string(item, "material", index, json_path),
				"textures": load_textures(item, index, json_path),
			}
		)

	return entries


def write_header(path: Path) -> None:
	path.parent.mkdir(parents=True, exist_ok=True)
	path.write_text(
		"""#pragma once

// AUTO-GENERATED by Game/Tool/gen_npc_config.py — do not edit by hand.

#include <game/GameApi.h>

#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

struct NpcConfigTextures
{
	char const* albedo;
	char const* metalness_glossiness;
	char const* normal;
};

struct NpcConfigEntry
{
	int32_t id;
	char const* name;
	char const* const* models;
	std::size_t model_count;
	char const* material;
	NpcConfigTextures textures;
};

class GAME_API NpcConfig
{
public:
	static std::span<NpcConfigEntry const> All() noexcept;
	static std::size_t Count() noexcept;
	static NpcConfigEntry const* FindById(int32_t id) noexcept;
	static NpcConfigEntry const* FindByName(std::string_view name) noexcept;
};
""",
		encoding="utf-8",
		newline="\n",
	)


def write_source(path: Path, entries: list[dict], json_path: Path) -> None:
	path.parent.mkdir(parents=True, exist_ok=True)
	repo_root = Path(__file__).resolve().parents[2]
	try:
		source_path = json_path.resolve().relative_to(repo_root).as_posix()
	except ValueError:
		source_path = json_path.name

	lines = [
		"#include <Data/generated/NpcConfig.gen.h>",
		"",
		"// AUTO-GENERATED by Game/Tool/gen_npc_config.py — do not edit by hand.",
		f"// Source: {source_path}",
		"",
		"namespace",
		"{",
	]

	if entries:
		for entry in entries:
			array_name = f"kNpc_{entry['id']}_Models"
			lines.append(f"\tchar const* const {array_name}[] =")
			lines.append("\t{")
			for model_path in entry["models"]:
				lines.append(f'\t\t"{cpp_escape(model_path)}",')
			lines.append("\t};")
			lines.append("")

		lines.append("\tNpcConfigEntry const kNpcEntries[] =")
		lines.append("\t{")
		for entry in entries:
			array_name = f"kNpc_{entry['id']}_Models"
			count = len(entry["models"])
			tex = entry["textures"]
			lines.append(
				"\t\t{ "
				f'{entry["id"]}, "{cpp_escape(entry["name"])}", {array_name}, {count}, '
				f'"{cpp_escape(entry["material"])}", '
				f'{{ "{cpp_escape(tex["albedo"])}", '
				f'"{cpp_escape(tex["metalness_glossiness"])}", '
				f'"{cpp_escape(tex["normal"])}" }} }},'
			)
		lines.append("\t};")
	else:
		lines.extend(
			[
				"\tchar const* const kNpc_Empty_Models[] = { nullptr };",
				"",
				"\tNpcConfigEntry const kNpcEntries[] =",
				"\t{",
				'\t\t{ 0, "", kNpc_Empty_Models, 0, "", { "", "", "" } },',
				"\t};",
			]
		)

	lines.extend(
		[
			"} // namespace",
			"",
			"std::span<NpcConfigEntry const> NpcConfig::All() noexcept",
			"{",
			"\treturn std::span<NpcConfigEntry const>(kNpcEntries, Count());",
			"}",
			"",
			"std::size_t NpcConfig::Count() noexcept",
			"{",
			f"\treturn {len(entries)};",
			"}",
			"",
			"NpcConfigEntry const* NpcConfig::FindById(int32_t id) noexcept",
			"{",
			"\tfor (NpcConfigEntry const& entry : All())",
			"\t{",
			"\t\tif (entry.id == id)",
			"\t\t{",
			"\t\t\treturn &entry;",
			"\t\t}",
			"\t}",
			"\treturn nullptr;",
			"}",
			"",
			"NpcConfigEntry const* NpcConfig::FindByName(std::string_view name) noexcept",
			"{",
			"\tfor (NpcConfigEntry const& entry : All())",
			"\t{",
			"\t\tif (name == entry.name)",
			"\t\t{",
			"\t\t\treturn &entry;",
			"\t\t}",
			"\t}",
			"\treturn nullptr;",
			"}",
			"",
		]
	)

	path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main(argv: list[str] | None = None) -> int:
	parser = argparse.ArgumentParser(description="Generate NpcConfig C++ class from npc.json")
	parser.add_argument("--input", type=Path, required=True, help="Path to npc.json")
	parser.add_argument("--header", type=Path, required=True, help="Output header path")
	parser.add_argument("--source", type=Path, required=True, help="Output source path")
	args = parser.parse_args(argv)

	entries = load_entries(args.input.resolve())
	write_header(args.header.resolve())
	write_source(args.source.resolve(), entries, args.input.resolve())

	print(f"Generated {args.header} and {args.source} ({len(entries)} npc entries)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
