// DON'T EDIT THIS FILE. Automatically generated by TableGen.py

namespace RenderWorker
{
	namespace TexCompressionLUT
	{
		extern uint8_t EXPAND5[32];
		extern uint8_t EXPAND6[64];
		extern uint8_t EXPAND7[128];
		extern uint8_t O_MATCH5[256][2];
		extern uint8_t O_MATCH6[256][2];
		extern uint8_t O_MATCH7[256][2];
		extern uint8_t QUANT_5_TAB[272];
		extern uint8_t QUANT_6_TAB[272];
		extern uint16_t ETC1_INVERSE_LOOKUP[64][256];
	}
}
